version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db_sandbox
    environment:
      MYSQL_DATABASE: db_sandbox
      # So you don't have to use root, but you can if you like
      MYSQL_PASSWORD: root
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_sandbox:/var/lib/mysql
# Names our volume
volumes:
      db_sandbox: